name: Windows Build (EXE + Installer)

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    env:
      APP_NAME: SprigOpenRecover
      # Use tag as version if present, else run number
      APP_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || github.run_number }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean old build
        shell: pwsh
        run: |
          if (Test-Path dist)  { Remove-Item dist  -Recurse -Force }
          if (Test-Path build) { Remove-Item build -Recurse -Force }

      - name: Build EXE (PyInstaller)
        shell: pwsh
        run: |
          # NOTE: --paths src is essential for a src/ layout
          pyinstaller -F -w `
            --name $env:APP_NAME `
            --paths src `
            --add-data "src/openrecover/assets/spriglogo.png;openrecover/assets" `
            src/main.py
          if (!(Test-Path "dist\$env:APP_NAME.exe")) { throw "EXE not produced" }

      - name: Locate built EXE
        shell: pwsh
        run: Get-ChildItem dist | Select-Object Name,Length,LastWriteTime

      - name: Install Inno Setup
        shell: pwsh
        run: choco install innosetup --no-progress -y

      - name: Build installer (Inno Setup)
        shell: pwsh
        run: |
          $dist = (Resolve-Path dist).Path
          $iscc = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
          & $iscc "installer\OpenRecoverProQt.iss" /DReleaseDist="$dist" /DAppVersion="$env:APP_VERSION" /DAppName="$env:APP_NAME"

      - name: Show installer output
        shell: pwsh
        run: Get-ChildItem installer\output | Select-Object Name,Length,LastWriteTime

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-${{ env.APP_VERSION }}
          path: |
            dist/*.exe
            installer/output/*.exe
