name: Windows Build (EXE + Installer)

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          # harden against subtle import misses during freezing
          pip install pyinstaller

      - name: Clean old build
        shell: pwsh
        run: |
          if (Test-Path dist)   { Remove-Item dist   -Recurse -Force }
          if (Test-Path build)  { Remove-Item build  -Recurse -Force }
          New-Item -ItemType Directory -Path dist | Out-Null
          if (-not (Test-Path installer/dist)) { New-Item -ItemType Directory -Path installer/dist | Out-Null }

      # ---- Single admin EXE (Qt UI) ----
      - name: Build EXE (single Admin build)
        shell: pwsh
        run: |
          # Build SprigOpenRecover.exe with PyInstaller
          pyinstaller -F -w `
            -n SprigOpenRecover `
            src/main.py `
            --hidden-import PySide6 `
            --hidden-import PySide6.QtCore `
            --hidden-import PySide6.QtGui `
            --hidden-import PySide6.QtWidgets `
            --add-data "src\openrecover\assets\spriglogo.png;openrecover\assets"

          # Move the EXE where the installer script expects it (installer/dist)
          Copy-Item ".\dist\SprigOpenRecover.exe" ".\installer\dist\SprigOpenRecover.exe" -Force

      - name: Install Inno Setup
        run: choco install innosetup -y --no-progress

      - name: Build installer
        shell: pwsh
        run: |
          $dist = Join-Path $env:GITHUB_WORKSPACE "installer\dist"
          $ver  = "${{ github.ref_name }}"
          if (-not $ver -or $ver -eq "") { $ver = "0.7-ci" }
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" `
            "/DReleaseDist=$dist" `
            "/DAppVersion=$ver" `
            installer\OpenRecoverProQt.iss

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist\SprigOpenRecover.exe
            installer\Output\*.exe
