name: Windows Build (EXE + Installer)

on:
  push:
    branches: [ main ]
    tags:     [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Clean old build
        shell: pwsh
        run: |
          if (Test-Path dist)  { Remove-Item dist -Recurse -Force }
          if (Test-Path build) { Remove-Item build -Recurse -Force }

      # Build a single Admin EXE (raw-disk access needs elevation)
      - name: Build EXE (PyInstaller)
        shell: pwsh
        run: |
          $logo = "src/openrecover/assets/spriglogo.png"
          $main = "src/main.py"
          pyinstaller -F -w `
            --name SprigOpenRecover `
            --uac-admin `
            --hidden-import PySide6 `
            --hidden-import PySide6.QtCore `
            --hidden-import PySide6.QtGui `
            --hidden-import PySide6.QtWidgets `
            --add-data "$logo;openrecover/assets" `
            $main

      - name: Locate built EXE
        id: findexe
        shell: pwsh
        run: |
          $dist = (Resolve-Path "dist").Path
          $exe  = Join-Path $dist "SprigOpenRecover.exe"
          if (!(Test-Path $exe)) { throw "SprigOpenRecover.exe not found in $dist" }
          "dist=$dist" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "exe=$exe"   | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Install Inno Setup
        shell: pwsh
        run: choco install innosetup --no-progress

      - name: Build installer (Inno Setup)
        shell: pwsh
        run: |
          $dist = "${{ steps.findexe.outputs.dist }}"
          $ver  = "${{ github.run_number }}"
          iscc "installer\OpenRecoverProQt.iss" /DReleaseDist="$dist" /DAppVer="$ver"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist\SprigOpenRecover.exe
            installer\Output\*.exe
